# This is a basic workflow to help you get started with Actions

name: Create markdown indexes

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - uses: DaanV2/Markdown-Action-Create-Indexes@v1.7.0
        with: 
          folder: ${{github.workspace}}/Documentation
          filename: 'README.md'

      - name: Commit changes
        continue-on-error: true
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name documentation-bot
          git config user.email bot@documentation.com
          git add .
          git commit -m "auto: Generated markdown indexes pages"
          git push